function [Inte] = OAM_GEN(Beam,dscale,L,Dz)

%code for generating OAM diffraction grating and OAM light
%35 mm plate and grating generated by interfering plane wave and beamwith
%helical phase.All units in SI


% dscale is spacing in SI for generating x,y matrix 
N      = L/dscale;
scale  = (-N/2:N/2-1)*dscale;
I      = 1;%intensity of two waves kept same for simplicity
lamb   = 630*1e-9;% wavelength of 650nm
k      = 2*pi/lamb;
F      = 1; %Horizontal Adjustment factor
ll     = 1;%order of OAM
[x,y]  = meshgrid(scale);
Patt   = abs(I*exp(1i*k.*(x))+I*exp(1i*ll.*atan2(y,x)));
%Patt(3501,3501) = Patt(3501,3502);
figure;
image(Patt,'CDataMapping','scaled')

M = Patt;
Mm = mean(Patt(:));
M(M>Mm)  = 1;
M(M~=1) = 0;
figure
image(M,'CDataMapping','scaled')
Beam    = Beam.*M;
figure
image(abs(Beam),'CDataMapping','scaled')

%generation of Diffraction pattern

[Uout,x2,y2] = fraunhofer_prop(Beam,lamb,dscale,Dz);
figure;

%Uout = Angular_spect(Beam,dscale,lamb,Dz);

Inte = abs((fftshift(Uout))).^2;% intensity
image(log(Inte),'CDataMapping','scaled')% image plane
%plot(1:length(x2),Inte(y2==0))